version: "3.8"

services:
  mongo:
    image: mongo
    container_name: todo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis
    container_name: todo-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  app:
    image: todo-backend
    container_name: todo-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - DEBUG=express-server:*
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
    ports:
      - 3000:3000
volumes:
  mongo_data: null
  redis_data: null
