version: "3.8"
name: todo-app-dev

services:
  todo-frontend-dev:
    image: todo-frontend-dev
    container_name: todo-frontend-nginx-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
      - PORT=3001
  todo-backend-dev:
    image: todo-backend-dev
    container_name: todo-backend-nginx-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - DEBUG=express-server:*
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
  mongo:
    image: mongo
    container_name: todo-mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis
    container_name: todo-redis-dev
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:1.20.1
    container_name: todo-reverse-proxy-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - todo-frontend-dev
      - todo-backend-dev
volumes:
  mongo_data: null
  redis_data: null
